server:
  port: 9001

web:
  upload-path: E:/deposit/

spring:
  datasource:
    url: jdbc:sqlserver://10.10.10.155;databaseName=finance-test;allowMultiQueries=true
    username: sa
    password: 1qazxsw2~
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  thymeleaf:
      cache: false
      mode: HTML
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB

mybatis:
  type-aliases-package: com.honji.order


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
#    typeEnumsPackage: com.honji.exhibition.admin.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#      auto-mapping-unknown-column-behavior: warning
    global-config:
      db-config:
        update-strategy: ignored #更新所有字段

pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


logging:
  file: logs/ccb.log
  level:
    com.honji.order.mapper: debug
    root: INFO
