server:
  port: 9999

web:
  upload-path: D:/deposit/

spring:
  datasource:
    url: jdbc:sqlserver://10.10.10.155;databaseName=finance-test
    username: sa
    password: 1qazxsw2~
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  thymeleaf:
      cache: false
      mode: HTML
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

mybatis:
  type-aliases-package: com.honji.order


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
#    typeEnumsPackage: com.honji.exhibition.admin.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    global-config:
          db-config:
            update-strategy: ignored

pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


logging:
  file: logs/ccb.log
  level:
    com.honji.order.mapper: debug
    root: INFO
